name: mopub_flutter_example
description: Demonstrates how to use the mopub_flutter plugin.
publish_to: 'none'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  mopub_flutter:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
